### ISSUE TITLE
Button styling

### ISSUE THREAD

**Issue by WeiLiangTan** [sonaye/react-native-micro-animated-button#14]
Hi, I have some problem will trying to style this button.

1) Is the minWidth & maxWidth necessary to have a default?
 When I'm trying to use flex:1 or width:"100%" to have it dynamically adjust the width, maxWidth will always force it to 240, where as I'm trying not to add the dimension.

2) Is it possible to remove the border?
  I tried by setting backgroundColor={"blue"} & foregroundColor={"white"}, after that I have tried to set borderWidth, borderColor, but can't remove it.

It would be great if I can get some help for these 2 problems, so that I can use it for my app that's going to launch soon.

Thanks.

**Comment by sonaye** [comment]
You can achieve both using the style prop.

```javascript
export default () => (
  <View style={{ flex: 1, justifyContent: 'center' }}>
    <Btn
      backgroundColor="yellow"
      foregroundColor="black"
      label="Btn"
      noRadius
      style={{ borderWidth: 0, width: '100%' }}
    />
  </View>
);
```

In this example however you lose the width animation feature (I would assume you no longer want it), since we are overwriting the `width` style prop here.

If you want the button to adapt to its parent's container width, you can utilize `onLayout`, but the button should be rendered only after you have the exact value of the parent's width. In `Animated` we need to define the interpolation points as numbers and not percentages.

```javascript
export default class extends Component {
  state = { width: null, ready: false };

  onLayout = e =>
    this.setState({ width: e.nativeEvent.layout.width, ready: true });

  render() {
    return (
      <View
        onLayout={this.onLayout}
        style={{ alignItems: 'center', flex: 1, justifyContent: 'center' }}>
        {this.state.ready && (
          <Btn
            backgroundColor="yellow"
            foregroundColor="black"
            label="Btn"
            maxWidth={this.state.width}
            noRadius
            style={{ borderWidth: 0 }}
          />
        )}
      </View>
    );
  }
}
```

**Comment by WeiLiangTan** [comment]
I see. Thanks for the reply.
